server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:db/liquibase-changelog.yml
    default-schema: public
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/water_Shop
    username: postgres
